version: '3'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB
      FLASK_ENV: development
      SECRET_KEY: $SECRET_KEY
      APP_URL: $APP_URL
      REDIS_URL: redis://redis:6379
    volumes:
      - ./api/app:/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  front:
    build: ./front
    ports:
      - "8000:8000"
    environment:
      VUE_APP_API_URL: $API_URL
    volumes:
      - ./front/app:/app
    restart: always

  redis:
    build: ./redis
    restart: always

volumes:
  postgres_data:
