version: '3'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB
      FLASK_ENV: development
      SECRET_KEY: $SECRET_KEY
    volumes:
      - ./api/app:/app/
    restart: always

  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/app:/app
    restart: always

  redis:
    build: ./redis
    restart: always

volumes:
  postgres_data:
