"""empty message

Revision ID: 32733ef51b47
Revises: 
Create Date: 2024-03-19 19:17:44.125185

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32733ef51b47"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_type", sa.String(length=32), nullable=False),
        sa.Column("translation", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("gender", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("words")
    # ### end Alembic commands ###
