"""empty message

Revision ID: 3f7e5158d6b1
Revises: 675a46399177
Create Date: 2025-03-15 13:14:40.242649

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f7e5158d6b1"
down_revision = "675a46399177"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_constraint("answers_word_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "words", ["word"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key("answers_word_fkey", "words", ["word"], ["id"])

    # ### end Alembic commands ###
