"""empty message

Revision ID: 5bb39bbd03f1
Revises: c7e510615903
Create Date: 2024-04-01 13:22:30.251319

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bb39bbd03f1"
down_revision = "c7e510615903"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("picture", sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_column("picture")

    # ### end Alembic commands ###
