"""empty message

Revision ID: 675a46399177
Revises: 9c0a5a4610cc
Create Date: 2025-03-07 13:16:42.921951

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "675a46399177"
down_revision = "9c0a5a4610cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=2048), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
