"""empty message

Revision ID: 90176428eda4
Revises: 90a308857c23
Create Date: 2024-03-31 13:49:12.437426

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "90176428eda4"
down_revision = "90a308857c23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decks", schema=None) as batch_op:
        level_enum = postgresql.ENUM(
            "EASY",
            "MEDIUM",
            "HARD",
            name="decklevel",
            create_type=False,
        )
        level_enum.create(batch_op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column("level", level_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.drop_column("level")

    # ### end Alembic commands ###
