"""empty message

Revision ID: 90a308857c23
Revises: 32733ef51b47
Create Date: 2024-03-22 22:21:06.936972

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a308857c23"
down_revision = "32733ef51b47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_deck",
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_deck")
    op.drop_table("decks")
    # ### end Alembic commands ###
