"""empty message

Revision ID: 9c0a5a4610cc
Revises: a20c949505bf
Create Date: 2024-05-09 18:00:29.785439

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c0a5a4610cc"
down_revision = "a20c949505bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profile_deck",
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_deck")
    op.drop_table("profiles")
    # ### end Alembic commands ###
