"""empty message

Revision ID: a20c949505bf
Revises: 5bb39bbd03f1
Create Date: 2024-04-01 21:16:36.955201

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a20c949505bf"
down_revision = "5bb39bbd03f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_date", sa.DateTime(), nullable=True))

    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_date", sa.DateTime(), nullable=True))

    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_date", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_column("created_date")

    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.drop_column("created_date")

    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_column("created_date")

    # ### end Alembic commands ###
