"""empty message

Revision ID: c7e510615903
Revises: 
Create Date: 2024-04-01 10:46:42.889261

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c7e510615903"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "level",
            postgresql.ENUM("EASY", "MEDIUM", "HARD", name="decklevel"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recto", sa.String(length=256), nullable=False),
        sa.Column("verso", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_deck",
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_deck")
    op.drop_table("answers")
    op.drop_table("words")
    op.drop_table("decks")
    # ### end Alembic commands ###
