name: Run script on push to main when front is updated

on:
  push:
    branches:
      - main
    paths:
      - "front/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build front image
        run: docker build -t ghcr.io/${{ github.repository }}/front:latest ./front

      - name: Push front image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/front:latest
