name: Run script on push to main when db is updated

on:
  push:
    branches:
      - main
    paths:
      - "db/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build db image
        run: docker build -t ghcr.io/${{ github.repository }}/db:latest ./db

      - name: Push db image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/db:latest
